# Generated by Django 3.0.5 on 2020-07-01 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.BooleanField(default=False)),
                ('post', models.CharField(max_length=280)),
                ('upVote', models.IntegerField(default=0)),
                ('downVote', models.IntegerField(default=0)),
                ('totalVote', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
